# Minimal wrangler.toml for Cloudflare Pages
# This file is intentionally minimal as Pages configuration
# should be done through the Cloudflare dashboard
name = "devtoolbox"
compatibility_date = "2024-01-01"